// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_ExportTest_RCPPEXPORTS_H_GEN_
#define RCPP_ExportTest_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace ExportTest {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("ExportTest", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("ExportTest", "_ExportTest_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in ExportTest");
            }
        }
    }

    inline void hello_world() {
        typedef SEXP(*Ptr_hello_world)();
        static Ptr_hello_world p_hello_world = NULL;
        if (p_hello_world == NULL) {
            validateSignature("void(*hello_world)()");
            p_hello_world = (Ptr_hello_world)R_GetCCallable("ExportTest", "_ExportTest_hello_world");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_hello_world();
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
    }

}

#endif // RCPP_ExportTest_RCPPEXPORTS_H_GEN_
