// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/ExportTest.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// hello_world
void hello_world();
static SEXP _ExportTest_hello_world_try() {
BEGIN_RCPP
    hello_world();
    return R_NilValue;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _ExportTest_hello_world() {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_ExportTest_hello_world_try());
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int _ExportTest_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("void(*hello_world)()");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _ExportTest_RcppExport_registerCCallable() { 
    R_RegisterCCallable("ExportTest", "_ExportTest_hello_world", (DL_FUNC)_ExportTest_hello_world_try);
    R_RegisterCCallable("ExportTest", "_ExportTest_RcppExport_validate", (DL_FUNC)_ExportTest_RcppExport_validate);
    return R_NilValue;
}
