# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello_world <- function() {
    invisible(.Call('_ExportTest_hello_world', PACKAGE = 'ExportTest'))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_ExportTest_RcppExport_registerCCallable', PACKAGE = 'ExportTest')
})
